defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

path: ???
experiment_name: ""
resume: ""
out_dir: "./runs"
n_iterations: 30000
with_gui: false
gui_update_from_device: true
val_frequency: 5000
num_workers: 24
use_wandb: false
wandb_project: "3dgrt"
test_last: true
validate_first: false
log_frequency: 1
compute_extra_metrics: true

enable_frame_timings: false

enable_writer: true
writer:
  hit_stat_frequency: 999999
  max_num_hits: 128
  log_image_views: ${int_list:[ 0, 13, 27, 43, 78 ]}

export_ingp:
  enabled: true
  force_half: false
  path: ""
import_ingp:
  enabled: false
  path: ""
  init_global_step: 0

export_ply:
  enabled: False 
  path: ""
import_ply:
  enabled: False 
  path: ""
  init_global_step: 0
  
model:
  strategy: GSStrategy # The strategy used for densification and pruning
  density_activation: sigmoid
  scale_activation: exp
  default_density: 0.1
  optimize_density: true
  optimize_features_albedo: true
  optimize_features_specular: true
  optimize_position: true
  optimize_rotation: true
  optimize_scale: true
  bvh_update_frequency: 1
  progressive_training:
    feature_type: "sh" # one of [sh, mlp], currently only sh supported
    init_n_features: 0 # sh: initial sh deg | mlp: num of dims initially unmasked
    max_n_features: 3 # sh: maximum sh deg | mlp: total num of dims finally unmasked
    increase_frequency: 1000 # unmask more feature dimensions every N global steps
    increase_step: 1 # sh: how many degrees unmasked per step | mlp: how many dims unmasked per step

  density_decay:
    gamma: 0.99
    start_iteration: -1 # 500
    end_iteration: -1 # 15000
    frequency: 50

  background:
    name: background-color # one of [skip-background, background-color]
    color: black # one of [black, white, random] needs to be defined if name == background-color

  print_stats: true

  densify:
    params: positions # one of [positions, positions_gradient_norm, features_albedo]
    frequency: 300 # densification_interval in 3DGS with default value 100
    start_iteration: 500 # densify_from_iter in 3DGS default value 500
    end_iteration: 15000 # densify_until_iter in 3DGS default value 15_000
    clone_grad_threshold: 0.0002 # Called densify_grad_threshold in 3DGS with default value 0.0002
    split_grad_threshold: 0.0002 # Called densify_grad_threshold in 3DGS with default value 0.0002
    relative_size_threshold: 0.01 # Gaussians larger than relative_size_threshold * scene_extent will be split not cloned. Called percent_dense in 3DGS with default value 0.01
    split:
      n_gaussians: 2 # Hardcoded to 2 in 3DGS
    share_density: false # share the original gaussian density among the new ones

  # They use the same values for pruning and densification so check the above values
  prune:
    frequency: 100
    start_iteration: 500
    end_iteration: 15000
    density_threshold: 0.01 # All Gaussians with the density lower than this will be pruned away

  prune_weight:
    frequency: 100
    start_iteration: -1
    end_iteration: -1
    weight_threshold: 0.5

  prune_scale:
    frequency: 100
    start_iteration: -1
    end_iteration: -1
    threshold: 1.0

  # Start and end iteration are not used in 3DGS
  reset_density:
    frequency: 3000 # Opacity reset interval in 3DGS default value 3000
    start_iteration: 0
    end_iteration: ${model.densify.end_iteration}
    # This parameter is hardcoded in the 3DGS to 0.01
    new_max_density: 0.01 # The density of the all the Gaussians will be set to min(density, this)

checkpoint:
  iterations: ${int_list:[ 7000, 30000 ]}

optimizer:
  type: adam # We only support adam for now
  lr: 0.01
  eps: 1.e-15
  params:
    positions:
      lr: 0.00016 # 3DGS value: 0.00016 initial and decayed to 0.0000016
    density:
      lr: 0.05 # 3DGS value: 0.05
    features_albedo:
      lr: 0.0025 # 3DGS value: 0.0025
    features_specular:
      lr: ${div:${optimizer.params.features_albedo.lr},20} # 3DGS value 20x smaller than lr of features_albedo
    rotation:
      lr: 0.001 # 3DGS value: 0.001
    scale:
      lr: 0.005 # 3DGS value: 0.005

scheduler:
  positions:
    # In the 3DGS paper they additionally have a parameter lr_delay_mult, but is is not being used so I drop it here
    type: exp
    lr_init: ${optimizer.params.positions.lr}
    lr_final: 0.0000016

    max_steps: 30000

  density:
    type: skip

render:
  method: 3dgrt # 3dgrt or 3dgut
  pipeline_type: reference
  backward_pipeline_type: ${render.pipeline_type}Bwd
  particle_kernel_degree: 4
  particle_kernel_density_clamping: true
  particle_kernel_min_response: 0.0113
  particle_kernel_min_alpha: ${div:1.0,255.0}
  particle_kernel_max_alpha: 0.99
  particle_radiance_sph_degree: 3
  primitive_type: instances
  min_transmittance: 0.001
  max_consecutive_bvh_update: 15
  enable_normals: false
  enable_hitcounts: true
  enable_kernel_timings: false

  splat: # 3DGUT-specific settings
    # culling
    rect_bounding: true
    tight_opacity_bounding: true
    tile_based_culling: true
    # projection
    n_rolling_shutter_iterations: 5
    ut_alpha: 1.0
    ut_beta: 2.0
    ut_kappa: 0.0
    ut_in_image_margin_factor: 0.1
    ut_require_all_sigma_points_valid: false
    # rendering
    k_buffer_size: 0  # 0 means unsorted
    global_z_order: true

loss:
  use_l1: true
  lambda_l1: 0.8
  use_l2: false
  lambda_l2: 1.0
  use_ssim: true
  lambda_ssim: 0.2

hydra:
  output_subdir: null
  job:
    chdir: false
  run:
    dir: .
